"use client";

import { useState } from "react";
import Image from "next/image";
import { motion, useScroll, useTransform } from "motion/react";
import {
  ArrowDown, ArrowRight, BarChart3, Bluetooth, Building2, CalendarDays,
  ChevronDown, CircleDot, Cpu, Gauge, Layers3, Menu, Network,
  Radio, Smartphone, Sparkles, Trophy, Users, Waves, X, Zap, ShoppingBag,
} from "lucide-react";

const reveal = { hidden: { opacity: 0, y: 28 }, visible: { opacity: 1, y: 0, transition: { duration: .7, ease: [0.22, 1, 0.36, 1] as const } } };
const stagger = { visible: { transition: { staggerChildren: .08 } } };

function Reveal({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return <motion.div className={className} variants={reveal} initial="hidden" whileInView="visible" viewport={{ once: true, amount: .16 }}>{children}</motion.div>;
}
function SectionTitle({ eyebrow, title, copy }: { eyebrow: string; title: string; copy?: string }) {
  return <Reveal className="mb-12 md:mb-20"><p className="eyebrow mb-5">{eyebrow}</p><h2 className="text-balance max-w-3xl text-4xl font-medium tracking-[-.045em] md:text-6xl">{title}</h2>{copy && <p className="mt-6 max-w-xl text-base leading-7 text-[#9ca3af] md:text-lg">{copy}</p>}</Reveal>;
}

const services = [
  ["Anniversaires", "Une expérience spectaculaire, pensée pour rassembler.", Sparkles],
  ["Team building", "Le collectif en mouvement autour d'un défi inédit.", Users],
  ["Conventions", "Une activation technologique qui marque les esprits.", Building2],
  ["EVG / EVJF", "Un moment intense, accessible et mémorable.", Zap],
  ["Festivals", "Des expériences fluides conçues pour les grands publics.", CalendarDays],
  ["Sur mesure", "Votre événement, transformé par nos technologies.", Waves],
];
const technology = [["Capteurs intelligents", Cpu], ["Temps réel", Radio], ["Scoring", Trophy], ["Projection", Layers3], ["Application mobile", Smartphone], ["Statistiques", BarChart3], ["Synchronisation", Network], ["Architecture évolutive", Gauge]];
const audiences = [["Collectivités", "Créer du lien dans l'espace public."], ["Festivals", "Faire vivre un moment collectif."], ["Entreprises", "Engager autrement les équipes."], ["Centres sportifs", "Renouveler l'expérience physique."]];
const faqs = [
  ["Qu'est-ce que CODATECH ?", "CODATECH est une entreprise française qui imagine, développe et déploie des technologies interactives pour le monde réel."],
  ["Quelle différence entre OARK et BattleSword ?", "OARK est notre socle technologique modulaire. BattleSword est une expérience de combat connecté développée à partir de notre savoir-faire."],
  ["Intervenez-vous sur des événements privés ?", "Oui. Nous proposons des formats adaptés aux anniversaires, team building, EVG/EVJF, conventions et festivals."],
  ["Pouvez-vous créer une expérience sur mesure ?", "Oui. Nous concevons la technologie, l'interface et le déploiement en fonction de votre idée et de votre public."],
];

function Navigation() {
  const [open, setOpen] = useState(false);
  const links = [["Technologies", "#technologies"], ["Prestations", "#prestations"], ["Boutique", "#boutique"]];
  return <header className="fixed inset-x-0 top-0 z-50 px-4 pt-4"><nav aria-label="Navigation principale" className="mx-auto flex h-14 max-w-6xl items-center justify-between rounded-2xl border border-white/[.08] bg-black/70 px-5 backdrop-blur-xl"><a href="#top" aria-label="CODATECH, accueil" className="text-sm font-semibold tracking-[.2em]">CODATECH</a><div className="hidden items-center gap-8 text-sm text-[#a6aab1] md:flex">{links.map(([l,h]) => <a key={l} href={h} className="transition hover:text-white">{l}</a>)}</div><a href="https://wa.me/33617114620?text=Bonjour%20CODATECH%2C%20j%27aimerais%20%C3%A9changer%20sur%20un%20projet." target="_blank" rel="noreferrer" className="hidden rounded-full bg-white px-4 py-2 text-xs font-medium text-black transition hover:bg-[#dcecff] md:block">Nous contacter</a><button className="md:hidden" onClick={() => setOpen(!open)} aria-expanded={open} aria-label="Ouvrir le menu">{open ? <X size={20}/> : <Menu size={20}/>}</button></nav>{open && <div className="mx-auto mt-2 max-w-6xl rounded-2xl border border-white/10 bg-[#0b0b0b] p-4 md:hidden">{links.map(([l,h]) => <a key={l} href={h} onClick={() => setOpen(false)} className="block rounded-xl px-3 py-3 text-sm text-[#b8bbc1]">{l}</a>)}<a href="https://wa.me/33617114620" target="_blank" rel="noreferrer" className="block rounded-xl px-3 py-3 text-sm text-white">Nous contacter</a></div>}</header>;
}

function HeroVisual() {
  return <div className="relative mx-auto aspect-square w-full max-w-[560px]" aria-hidden="true"><div className="absolute inset-[8%] rounded-full bg-[#4f9cf9]/15 blur-[90px]"/><motion.div animate={{ rotate: 360 }} transition={{ duration: 45, repeat: Infinity, ease: "linear" }} className="absolute inset-[10%] rounded-full border border-white/10"><span className="absolute left-1/2 top-0 h-2 w-2 -translate-x-1/2 -translate-y-1/2 rounded-full bg-[#8bc0ff] shadow-[0_0_25px_#4f9cf9]"/></motion.div><motion.div animate={{ rotate: -360 }} transition={{ duration: 32, repeat: Infinity, ease: "linear" }} className="absolute inset-[24%] rounded-full border border-dashed border-white/15"><span className="absolute bottom-[12%] left-[5%] h-1.5 w-1.5 rounded-full bg-white"/></motion.div><div className="glass absolute left-[18%] top-[22%] w-[64%] rounded-3xl p-5"><div className="mb-8 flex items-center justify-between"><span className="eyebrow">Live system</span><span className="flex items-center gap-2 text-[10px] text-emerald-300"><i className="h-1.5 w-1.5 rounded-full bg-emerald-400 shadow-[0_0_8px_#34d399]"/> Active</span></div><div className="flex h-24 items-end gap-1.5">{[32,48,39,72,54,88,63,78,45,68,91,59].map((h,i)=><motion.i key={i} initial={{height:0}} animate={{height:`${h}%`}} transition={{delay:.5+i*.04,duration:.7}} className="flex-1 rounded-full bg-gradient-to-t from-[#246fc9] to-[#8bc0ff]"/>)}</div><div className="mt-5 flex justify-between text-[10px] text-[#7f858e]"><span>12 sensors</span><span>4.8 ms</span><span>Synced</span></div></div><div className="glass absolute bottom-[11%] right-[3%] flex items-center gap-3 rounded-2xl px-4 py-3"><CircleDot size={16} className="text-[#75b4ff]"/><div><p className="text-[10px] text-[#858b94]">Signal</p><p className="text-xs">Connected</p></div></div><div className="glass absolute left-[3%] top-[14%] rounded-2xl p-3"><Bluetooth size={17} className="text-[#75b4ff]"/></div></div>;
}

export function CodatechLanding() {
  const { scrollYProgress } = useScroll(); const y = useTransform(scrollYProgress, [0, 1], [0, -100]);
  return <main id="top" className="ambient-color noise overflow-hidden bg-[#050505] text-[#f5f5f5]"><Navigation />
    <section className="relative flex min-h-screen items-center border-b border-white/[.06] px-6 pb-16 pt-28"><div className="grid-bg absolute inset-0"/><div className="absolute left-[18%] top-[15%] h-64 w-64 rounded-full bg-[#144985]/20 blur-[120px]"/><div className="relative mx-auto grid w-full max-w-7xl items-center gap-8 lg:grid-cols-[1.05fr_.95fr]"><motion.div initial="hidden" animate="visible" variants={stagger} className="pt-8"><motion.div variants={reveal} className="mb-8 flex items-center gap-3"><span className="h-px w-8 bg-[#4f9cf9]"/><span className="eyebrow">Technology in motion</span></motion.div><motion.h1 variants={reveal} className="text-[clamp(3.6rem,10vw,8.5rem)] font-semibold leading-[.8] tracking-[-.085em]">CODATECH</motion.h1><motion.h2 variants={reveal} className="text-balance mt-10 max-w-2xl text-3xl font-medium leading-tight tracking-[-.04em] md:text-5xl">We build technology<br/><span className="text-[#727780]">you can experience.</span></motion.h2><motion.p variants={reveal} className="mt-7 max-w-lg text-base leading-7 text-[#9ca3af]">Nous imaginons des technologies interactives qui transforment le mouvement, les lieux et les rencontres en expériences mémorables.</motion.p><motion.div variants={reveal} className="mt-9 flex flex-wrap gap-3"><a href="#technologies" className="group flex items-center gap-3 rounded-full bg-white px-6 py-3.5 text-sm font-medium text-black">Découvrir <ArrowDown size={15} className="transition group-hover:translate-y-1"/></a><a href="#contact" className="rounded-full border border-white/15 px-6 py-3.5 text-sm transition hover:bg-white/[.06]">Parler de votre projet</a></motion.div></motion.div><HeroVisual/></div></section>

    <div className="border-b border-white/[.06] px-6 py-8"><Reveal className="mx-auto flex max-w-6xl items-center justify-center gap-5 text-[#70757e]"><span className="h-px w-12 bg-gradient-to-r from-transparent to-white/15"/><Image src="/images/COD_solo.png" alt="Logo CODATECH" width={512} height={512} className="h-10 w-10 object-contain opacity-80"/><span className="font-mono text-[10px] uppercase tracking-[.24em]">Designed & developed by CODATECH</span><span className="h-px w-12 bg-gradient-to-l from-transparent to-white/15"/></Reveal></div>

    <section id="about" className="px-6 py-28 md:py-44"><div className="mx-auto grid max-w-6xl gap-16 lg:grid-cols-2"><SectionTitle eyebrow="01 — CODATECH" title="Nous donnons une forme aux idées." copy="CODATECH conçoit en France des technologies propriétaires et des expériences où le numérique rencontre le monde physique."/><Reveal><div className="relative aspect-[4/3] overflow-hidden rounded-[2rem] border border-white/[.08] bg-[#0b0b0b] p-8"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_30%,rgba(79,156,249,.16),transparent_40%)]"/><div className="absolute inset-[14%] rounded-full border border-white/10"/><div className="absolute inset-[27%] rounded-full border border-white/10"/><div className="absolute left-1/2 top-1/2 h-20 w-20 -translate-x-1/2 -translate-y-1/2 rounded-full border border-[#4f9cf9]/40 bg-[#4f9cf9]/10 shadow-[0_0_70px_rgba(79,156,249,.25)]"/><span className="absolute left-[20%] top-[28%] h-2 w-2 rounded-full bg-white shadow-[0_0_16px_white]"/><span className="absolute bottom-[22%] right-[24%] h-2 w-2 rounded-full bg-[#4f9cf9] shadow-[0_0_18px_#4f9cf9]"/></div></Reveal></div></section>

    <section id="technologies" className="border-y border-white/[.06] bg-[#0b0b0b] px-6 py-28 md:py-40"><div className="mx-auto max-w-6xl"><SectionTitle eyebrow="02 — Nos technologies" title="Deux innovations. Un même mouvement." copy="Des produits distincts, imaginés et développés par les équipes CODATECH."/><div className="grid gap-4 md:grid-cols-2"><Reveal><article className="group relative min-h-[480px] overflow-hidden rounded-[2rem] border border-white/[.08] bg-[#111] p-8"><div className="absolute inset-0 bg-[radial-gradient(circle_at_65%_30%,rgba(79,156,249,.2),transparent_35%)]"/><div className="absolute right-[12%] top-[12%] h-56 w-56 rounded-full border border-white/10 transition duration-700 group-hover:scale-110"/><p className="eyebrow relative">Connected platform</p><div className="absolute bottom-8 left-8 right-8"><h3 className="text-5xl font-semibold tracking-[-.06em]">OARK</h3><p className="mt-4 max-w-md text-sm leading-6 text-[#90959d]">Une technologie modulaire qui connecte équipements, espaces et activités en temps réel.</p><a href="/oark" className="mt-7 inline-flex items-center gap-2 text-xs text-[#78b5ff]">Découvrir OARK <ArrowRight size={14}/></a></div></article></Reveal><Reveal><article className="group relative min-h-[480px] overflow-hidden rounded-[2rem] border border-white/[.08] bg-[#111] p-8"><div className="absolute inset-0 bg-[linear-gradient(145deg,transparent_30%,rgba(79,156,249,.12))]"/><div className="absolute right-[8%] top-[25%] h-px w-[70%] -rotate-12 bg-gradient-to-r from-transparent via-[#83bdff] to-transparent shadow-[0_0_20px_#4f9cf9] transition duration-700 group-hover:rotate-[-8deg]"/><p className="eyebrow relative">Connected combat</p><div className="absolute bottom-8 left-8 right-8"><h3 className="text-5xl font-semibold tracking-[-.06em]">BattleSword</h3><p className="mt-4 max-w-md text-sm leading-6 text-[#90959d]">Le combat nouvelle génération : intuitif, connecté, spectaculaire et accessible à tous.</p><a href="/battlesword" className="mt-7 inline-flex items-center gap-2 text-xs text-[#78b5ff]">Découvrir BattleSword <ArrowRight size={14}/></a></div></article></Reveal></div></div></section>

    <section id="prestations" className="px-6 py-28 md:py-40"><div className="mx-auto max-w-6xl"><SectionTitle eyebrow="03 — Prestations" title="Des moments que l'on ne regarde pas. On les vit."/><motion.div variants={stagger} initial="hidden" whileInView="visible" viewport={{once:true}} className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{services.map(([title,copy,Icon],i)=><motion.article variants={reveal} key={String(title)} className="group min-h-64 rounded-3xl border border-white/[.08] bg-[#111] p-7 transition duration-500 hover:-translate-y-1 hover:border-[#4f9cf9]/30"><div className="mb-16 flex justify-between"><span className="grid h-11 w-11 place-items-center rounded-2xl border border-white/10 bg-white/[.03]"><Icon size={19} className="text-[#7bb8ff]"/></span><span className="font-mono text-[10px] text-[#555b64]">0{i+1}</span></div><h3 className="text-xl font-medium tracking-tight">{String(title)}</h3><p className="mt-3 max-w-xs text-sm leading-6 text-[#858b94]">{String(copy)}</p></motion.article>)}</motion.div></div></section>

    <section className="px-6 py-28 md:py-44"><div className="mx-auto max-w-6xl"><SectionTitle eyebrow="03 — Le processus" title="De l'idée au mouvement."/><div className="grid gap-px overflow-hidden rounded-3xl border border-white/[.08] bg-white/[.08] md:grid-cols-4">{["Créer","Connecter","Configurer","Jouer"].map((s,i)=><Reveal key={s} className="bg-[#080808] p-8 md:min-h-56"><span className="font-mono text-xs text-[#4f9cf9]">0{i+1}</span><div className="mt-20 flex items-center justify-between"><h3 className="text-2xl font-medium">{s}</h3>{i<3 && <ArrowRight size={17} className="text-[#555]"/>}</div></Reveal>)}</div></div></section>

    <section id="technologie" className="bg-[#0b0b0b] px-6 py-28 md:py-40"><div className="mx-auto max-w-6xl"><SectionTitle eyebrow="05 — Notre savoir-faire" title="Complexe à l'intérieur. Évident à utiliser."/><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{technology.map(([label,Icon])=><Reveal key={String(label)}><div className="group flex min-h-44 flex-col justify-between rounded-3xl border border-white/[.08] bg-[#111] p-6 transition hover:bg-[#151515]"><Icon size={20} className="text-[#6caeff]"/><p className="max-w-[140px] text-sm font-medium">{String(label)}</p></div></Reveal>)}</div><div className="mt-16 flex flex-wrap gap-3">{["Sans fil","Plug & Play","Personnalisable","Scalable","Faible latence","API évolutive"].map(x=><span key={x} className="rounded-full border border-white/10 px-5 py-2.5 text-xs text-[#a4a8af]">{x}</span>)}</div></div></section>

    <section className="px-6 py-28 md:py-44"><div className="mx-auto max-w-6xl"><SectionTitle eyebrow="05 — Pour qui ?" title="Une nouvelle dimension pour vos publics."/><div className="grid gap-4 md:grid-cols-2">{audiences.map(([a,b],i)=><Reveal key={a}><article className="group relative min-h-72 overflow-hidden rounded-[2rem] border border-white/[.08] bg-[#0b0b0b] p-8"><motion.div style={{y}} className="absolute -right-20 -top-20 h-64 w-64 rounded-full border border-white/[.07] bg-[radial-gradient(circle,rgba(79,156,249,.12),transparent_65%)]"/><span className="eyebrow">0{i+1}</span><div className="absolute bottom-8 left-8"><h3 className="text-3xl font-medium tracking-tight">{a}</h3><p className="mt-3 text-sm text-[#8d929a]">{b}</p></div></article></Reveal>)}</div></div></section>

    <section className="border-y border-white/[.06] bg-[#0b0b0b] px-6 py-24"><div className="mx-auto grid max-w-6xl gap-12 sm:grid-cols-2 lg:grid-cols-4">{[["100+","événements"],["5 000+","participants"],["100%","développé en France"],["∞","possibilités"]].map(([n,l])=><Reveal key={l}><p className="text-5xl font-medium tracking-[-.05em] md:text-6xl">{n}</p><p className="mt-3 text-sm text-[#858b94]">{l}</p></Reveal>)}</div></section>

    <section className="px-6 py-28 md:py-44"><div className="mx-auto max-w-6xl"><SectionTitle eyebrow="06 — Expériences" title="La technologie s'efface. L'expérience reste."/><div className="grid gap-4 md:grid-cols-5"><div className="group relative min-h-[430px] overflow-hidden rounded-[2rem] border border-white/[.08] bg-[#0c0c0c] md:col-span-3"><div className="absolute inset-0 bg-[radial-gradient(ellipse_at_35%_40%,rgba(79,156,249,.24),transparent_32%),linear-gradient(135deg,transparent,rgba(255,255,255,.03))] transition duration-700 group-hover:scale-105"/><div className="absolute left-[10%] top-[20%] h-px w-[75%] rotate-12 bg-gradient-to-r from-transparent via-[#6cb0ff] to-transparent shadow-[0_0_20px_#4f9cf9]"/><p className="absolute bottom-7 left-7 text-sm">Mouvement augmenté</p></div><div className="group relative min-h-[430px] overflow-hidden rounded-[2rem] border border-white/[.08] bg-[#0c0c0c] md:col-span-2"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_45%,rgba(79,156,249,.2),transparent_25%)]"/><div className="absolute left-1/2 top-[42%] h-40 w-40 -translate-x-1/2 -translate-y-1/2 rounded-full border border-white/10 transition duration-700 group-hover:scale-125"/><div className="absolute left-1/2 top-[42%] h-20 w-20 -translate-x-1/2 -translate-y-1/2 rounded-full border border-[#4f9cf9]/30"/><p className="absolute bottom-7 left-7 text-sm">Connexion instantanée</p></div></div></div></section>

    <section id="boutique" className="border-y border-white/[.06] bg-[#0b0b0b] px-6 py-28 md:py-40"><div className="mx-auto grid max-w-6xl items-center gap-16 lg:grid-cols-2"><Reveal><p className="eyebrow mb-5">07 — Boutique</p><h2 className="text-balance text-4xl font-medium tracking-[-.045em] md:text-6xl">Emportez l'expérience avec vous.</h2><p className="mt-6 max-w-lg text-base leading-7 text-[#9ca3af]">Équipements, accessoires et produits officiels CODATECH. Une sélection conçue avec la même exigence que nos technologies.</p><a href="/boutique" className="group mt-9 inline-flex items-center gap-3 rounded-full bg-white px-6 py-3.5 text-sm font-medium text-black">Visiter la boutique <ShoppingBag size={16}/></a></Reveal><Reveal><div className="relative aspect-[4/3] overflow-hidden rounded-[2rem] border border-white/[.08] bg-[#111]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_35%_35%,rgba(34,211,238,.2),transparent_32%),radial-gradient(circle_at_70%_65%,rgba(236,72,153,.16),transparent_36%)]"/><motion.div whileHover={{rotate:3,scale:1.04}} className="glass absolute left-1/2 top-1/2 grid h-52 w-40 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-[2rem]"><div className="text-center"><ShoppingBag className="mx-auto text-[#67d9e8]"/><p className="mt-5 bg-gradient-to-r from-[#67d9e8] to-[#ed72b3] bg-clip-text text-xs font-semibold tracking-[.2em] text-transparent">CODATECH</p><p className="mt-2 font-mono text-[9px] text-[#777d86]">OFFICIAL STORE</p></div></motion.div></div></Reveal></div></section>

    <section className="px-6 py-28"><div className="mx-auto max-w-4xl"><SectionTitle eyebrow="08 — FAQ" title="Quelques réponses, simplement."/><div>{faqs.map(([q,a])=><details key={q} className="group border-t border-white/10 py-6 last:border-b"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 text-base font-medium md:text-lg">{q}<ChevronDown size={18} className="shrink-0 transition group-open:rotate-180"/></summary><p className="max-w-2xl pt-5 text-sm leading-7 text-[#91969f]">{a}</p></details>)}</div></div></section>

    <section id="contact" className="relative overflow-hidden px-6 py-32 text-center md:py-52"><div className="absolute left-1/2 top-1/2 h-[500px] w-[700px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-[#205fa9]/15 blur-[120px]"/><Reveal className="relative mx-auto max-w-4xl"><p className="eyebrow mb-7">09 — Contact</p><h2 className="text-balance text-5xl font-medium tracking-[-.055em] md:text-8xl">Build what people will remember.</h2><p className="mx-auto mt-7 max-w-xl text-base leading-7 text-[#969ba4]">Une prestation, un partenariat ou une technologie à inventer ? Parlons de votre prochain projet.</p><a href="https://wa.me/33617114620?text=Bonjour%20CODATECH%2C%20j%27aimerais%20%C3%A9changer%20sur%20un%20projet." target="_blank" rel="noreferrer" className="group mx-auto mt-10 inline-flex items-center gap-3 rounded-full bg-white px-7 py-4 text-sm font-medium text-black">Discuter sur WhatsApp <ArrowRight size={16} className="transition group-hover:translate-x-1"/></a><a href="mailto:contact@oark.io" className="mx-auto mt-5 block w-fit text-sm text-[#8e949d] transition hover:text-white">contact@oark.io</a></Reveal></section>

    <footer className="border-t border-white/[.08] px-6 py-10"><div className="mx-auto flex max-w-6xl flex-col gap-8 text-xs text-[#777d86] md:flex-row md:items-center md:justify-between"><div><p className="font-semibold tracking-[.2em] text-white">CODATECH</p><p className="mt-2">Interactive technologies, made in France.</p></div><div className="flex flex-wrap gap-6"><a href="#technologies" className="hover:text-white">Technologies</a><a href="#prestations" className="hover:text-white">Prestations</a><a href="#boutique" className="hover:text-white">Boutique</a><a href="https://wa.me/33617114620" target="_blank" rel="noreferrer" className="hover:text-white">WhatsApp</a><a href="mailto:contact@oark.io" className="hover:text-white">contact@oark.io</a><a href="#" className="hover:text-white">Mentions légales</a><a href="#" className="hover:text-white">Confidentialité</a></div><p>© {new Date().getFullYear()} CODATECH</p></div></footer>
  </main>;
}
